# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Update Metadata
on:
  push:
     branches: [ main ]
  schedule:
    - cron: '*/20 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false 
        fetch-depth: 0 
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.7
    - run: python -m pip install --upgrade pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Get BANR Data
      run: |
        python get_BANR_BHZ_waveform_data.py
    - name: Get BANR Data in HHZ
      run: |
        python get_BANR_HHZ_waveform_data.py
    - name: Get BZS data
      run: |
        python get_BZS_waveform_data.py        
    - name: Get BMR Data
      run: |
        python get_BMR_waveform_data.py
    #- name: Get BUR01 Data () |
    #  run: |
    #    python get_BUR01_data.py
    - name: Get BZS data
      run: |
        python get_BZS_waveform_data.py
    - name: Get CJR BHZ data
      run: |
        python get_CJR_BHZ_waveform_data.py
    - name: Get CJR HHZ data
      run: |
        python get_CJR_HHZ_waveform_data.py
    - name: Get IASR Data in BHZ
      run: |
        python get_RO_IASR_BHZ_waveform_data.py
    - name: Get IASR Data in HHZ
      run: |
        python get_RO_IASR_HHZ_waveform_data.py
    - name: Get MLR Data in BHZ
      run: |
        python get_RO_MLR_BHZ_waveform_data.py
    - name: Get MLR Data in EHZ
      run: |
        python get_RO_MLR_EHZ_waveform_data.py
    - name: Get MLR Data in HHZ
      run: |
        python get_RO_MLR_waveform_data.py
    - name: Get VRI data in HHZ
      run: |
        python get_RO_VRI_HHZ_data.py
    #- name: Proceed adding file
    #  run: |
    #    git add .
        
    - name: commit files
      run: |
        git checkout main
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit --allow-empty -m "Update metadata" -a
        git config pull.rebase false
        git pull
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
